### ISSUE TITLE
Remove systemexit

### ISSUE THREAD

**Issue by salvacarrion** [lit26/finvizfinance#10]
**Problem:**

I would like to iterate over the `finvizfinance(ticker)` but since the `SystemExit` is present in the `webScrap` function, when there is an exception I cannot capture it, and the program simply exits:

```
    try:
        website = requests.get(url, headers=headers)
        website.raise_for_status()
        soup = BeautifulSoup(website.text, 'lxml')
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
    return soup
```

**Solution:**
- Change the exception type (e.g. LookupError, NameError,...)

**Comment by lit26** [comment]
You are right. I will fix this ASAP.

**Comment by lit26** [comment]
I have changed the error. Please update the package. Thanks for your advice.
