### ISSUE TITLE
QST: How do I select Index as NASDAQ 100 or RUSSELL 2000?

### ISSUE THREAD

**Issue by Jeraz** [lit26/finvizfinance#103]
### Question about finvizfinance

I am using python version 3.10.12 and finvizfinance library version 0.14.7. I am trying to run the filter for Index 'NASDAQ 100'  but I get an error stated below. I know the finviz web screener has those options for NASDAQ 100 and RUSSELL 2000. Can someone guide if I am missing something? Thank you!

raise ValueError(
ValueError: Invalid filter option 'NASDAQ'. Possible filter options: ['Any', 'S&P 500', 'DJIA']

**Comment by lit26** [comment]
It seems finviz add those two in the latest. I will update in the latest ASAP.

**Comment by Jeraz** [comment]
Thank you

**Comment by lit26** [comment]
Should be included in the latest.
