### ISSUE TITLE
How do you get Industry filter?

### ISSUE THREAD

**Issue by tombohub** [lit26/finvizfinance#11]
Hello, thanks for the package!

I am wondering how do you get Industries?

in code:
```python
filters_dict = {'Industry': "Silver"}
    performance = Performance()
    performance.set_filter(filters_dict=filters_dict)
    df = performance.ScreenerView()
    return df
```

Where do you get the proper filter for that industry? `ind_silver`

I want to make list of all filters, but I can't find them in your code. How do you generate filters?

Thanks

**Comment by lit26** [comment]
You can use the `getFilters()` and `getFilterOptions(screen_filter)` to get the filters. More details: https://finvizfinance.readthedocs.io/en/latest/screener.html.
The filter is scrapped from the website. 
Thanks

**Comment by tombohub** [comment]
Ok, thank you
