### ISSUE TITLE
proxy 

### ISSUE THREAD

**Issue by ericwbzhang** [lit26/finvizfinance#116]
You may forget to add the proxy ref at 

https://github.com/lit26/finvizfinance/blob/bad77166c8c9560d528e79189c1ca5784bc82450/finvizfinance/util.py#L59

**Comment by ericwbzhang** [comment]
PR #117

**Comment by ericwbzhang** [comment]
updated PR #119

**Comment by lit26** [comment]
This is updated in v1.1.0. Thanks for reporting.
