### ISSUE TITLE
How do I get a list with the ticker, company name, price and earnings date without making 2 requests?

### ISSUE THREAD

**Issue by atowersc** [lit26/finvizfinance#12]
I understand that when using the overview module, does not return the earnings date parameter. 
and when using the financial module returns the parameter earnings date, but the company name parameter does not return.  How can I get the 3 parameters without making 2 requests.

**Comment by lit26** [comment]
I will say it will be in the next version. It will depend on my availability.

**Comment by lit26** [comment]
The version is updated. Please use the custom screener in the new version.

**Comment by atowersc** [comment]
good. I run to prove it. ✌️👍

**Comment by atowersc** [comment]
has this problem. cloning the repository gets the file, but updating it from the terminal does not download it.

`FileNotFoundError: [Errno 2] No such file or directory: 'finvizfinance/util.json'`

**Comment by lit26** [comment]
Are you using git clone or from pypi?

**Comment by atowersc** [comment]
> So the git clone has no problem. But pypi will have the issue above?

exactly the git clone. it worked without problems. but when I went to implement it in my project and update the repository by pip, I did not download the file.

![Screenshot 2021-02-23 at 23 (1)](https://user-images.githubusercontent.com/78119341/108946816-32092c80-762d-11eb-857c-2d4f66a770d1.png)

![Screenshot 2021-02-23 at 23](https://user-images.githubusercontent.com/78119341/108946832-39303a80-762d-11eb-935d-36daf9b2cc7a.png)

**Comment by lit26** [comment]
I get it. When I set up the package, it only includes the .py file. I will find a way to fix it ASAP.

**Comment by lit26** [comment]
Should be fixed.

**Comment by atowersc** [comment]
**working without errors  :)**

**Comment by lit26** [comment]
Thanks a lot. 

Tianning Li
