### ISSUE TITLE
BUG: Insider Transactions returning errors

### ISSUE THREAD

**Issue by GilesAlonso** [lit26/finvizfinance#120]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
shared tyne with the bug present:

https://app.neptyne.com/-/3xvczeb5e6
```

### Issue Description

Code was working fine with latest capture of data around day 07/23/2024. Stopped giving responses and doesn't update captures.
There seems to exist a problem in  finvizfinance.insider.Insider

### Expected Behavior

Should display the list of Top Owner Trades, returns an error.

### Installed Versions

<details>

Replace this line with the output of finvizfinance.__version__
Using the most recent version.
</details>

**Comment by lit26** [comment]
This is fixed in v1.1.0. Thanks for reporting.
