### ISSUE TITLE
Change% bad interpretation

### ISSUE THREAD

**Issue by atowersc** [lit26/finvizfinance#16]
I ran into the following error. in the column of Change% does not interpret the amount well.
This error occurs in both the overview and Custom modules. I have not tried the others.

![Screenshot 2021-02-26 at 15](https://user-images.githubusercontent.com/78119341/109350284-40319580-7845-11eb-9bb0-47bfb3019ffe.png)

![Screenshot 2021-02-26 at 15 (1)](https://user-images.githubusercontent.com/78119341/109350292-43c51c80-7845-11eb-8ba8-25cd6e369d3d.png)

**Comment by lit26** [comment]
This is not the percentage. It's the actual number

**Comment by atowersc** [comment]
yes, but why is it interpreted differently? 6.38% is not the same as 0.0638%

**Comment by lit26** [comment]
6.38% = 0.0638. I don't have the percentage sign.

**Comment by atowersc** [comment]
Clear. I thought his vision was to show the change in percentage. clear with a simple operation is calculated... 
now. the question changes. with what intention is it shown in this format and not directly in percentage?

**Comment by lit26** [comment]
The percentage is clear for displaying. But if you do the calculation, you need to convert it back to the actual number. There is not much difference between the two.
