### ISSUE TITLE
See valuation/overview/... of specific set of tickers (not filtered through preset)

### ISSUE THREAD

**Issue by DidierRLopes** [lit26/finvizfinance#17]
Hey,

Great package! I'm using it on https://github.com/DidierRLopes/GamestonkTerminal :)

I was wondering, does your package allows you to see valuation,overview,... of specific tickers? E.g. https://finviz.com/screener.ashx?v=111&t=FB,AMZN,AAPL,AMD, rather than seeing those based on specified presets?

Thanks in advance!

**Comment by lit26** [comment]
Yes, I can use the code below.
```python
from finvizfinance.screener.overview import Overview

foverview = Overview()
ticker='FB,AMZN,AAPL,AMD'
foverview.set_filter(ticker=ticker)
df = foverview.ScreenerView()
```

**Comment by DidierRLopes** [comment]
That's exactly what I wanted!

Amazing, thank you so much!
