### ISSUE TITLE
Weekly chart not downloading

### ISSUE THREAD

**Issue by jy13249** [lit26/finvizfinance#18]
When I write stock.TickerCharts('weekly'), it is only downloading the daily timeframe chart and not the weekly chart

**Comment by lit26** [comment]
Hi, I have fixed the bug. There is a typo in the previous version. Please update to the latest version. 
Thanks for telling me.

**Comment by jy13249** [comment]
Just tested it and it's working. Thanks for the quick response and fix!

**Comment by lit26** [comment]
You are welcome.
