### ISSUE TITLE
Suggestion - timeout for scrapoing

### ISSUE THREAD

**Issue by camilo-rojas** [lit26/finvizfinance#21]
Hi thanks for the time here, im thinking of using your library, one suggestion:
In the Util.py - webscrap
website = requests.get(url, headers=headers)
You may want to setup a timeout, as this helps handle different use cases.
better if its handled from the Object constructor as an optional parameter.

Thanks again.

**Comment by lit26** [comment]
Thanks for your advice. I will implement it.

**Comment by lit26** [comment]
The package is updated. Please check the latest version.
