### ISSUE TITLE
scanner method

### ISSUE THREAD

**Issue by shahab-cl** [lit26/finvizfinance#23]
Hi Is there a way to add a reply to line 192 of overview.py

                raise ValueError("Invalid order {} .Possible values are {}".format (order,  self.getOrders()))

Please excuse the syntax error.

The same for line 73 

And line 41.

**Comment by lit26** [comment]
Yup, I will add them ASAP.

**Comment by lit26** [comment]
The package is updated. Please check the latest version. Thanks for your advice.
