### ISSUE TITLE
EPS next Y doesn't exist in TickerFundament

### ISSUE THREAD

**Issue by Roman-Isachenko** [lit26/finvizfinance#24]
Hi.
Thank you for the library.
Found one bug.
finvizfinance(symbol).TickerFundament() isn't contain 'EPS next Y' field from finviz.

Can you fix it, please?

**Comment by lit26** [comment]
![Screen Shot 2021-05-24 at 10 58 58](https://user-images.githubusercontent.com/51225681/119388390-12f75680-bc7f-11eb-9adb-65ca31417de6.png)
Can you show which stock you are using?

**Comment by lit26** [comment]
This issue will be closed due to inactivity.
