### ISSUE TITLE
Options in the arguments of the function

### ISSUE THREAD

**Issue by msh855** [lit26/finvizfinance#27]
Hi, thanks for the very useful library. 

But something that is missing in the documentation is that is not clear what are the options

In this example 

```
from finvizfinance.screener.overview import Overview

foverview = Overview()
filters_dict = {'Index':'S&P 500','Sector':'Basic Materials'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.ScreenerView()
df.head()
```

Cannot understand where I can find the number of different indices and the related information that can be filtered or passed as arguments.

**Comment by lit26** [comment]
You can get the options by checking the finviz website or use `getFilters()` and/or `getFilterOptions(screen_filter)`. For more detail, please check the document: https://finvizfinance.readthedocs.io/en/latest/screener.html.
