### ISSUE TITLE
Multiple exchange option

### ISSUE THREAD

**Issue by msh855** [lit26/finvizfinance#28]
Hi, 

How I can choose to download info only on two exchanges? i.e. NYSE and NASDAQ? 

I tried something like: 

```
[foverview = Overview()
filters_dict = {'Exchange': 'NYSE', 'Exchange': 'NASDAQ'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.ScreenerView()](url)
```

But it looks that it downloads info based only on the second filter.

**Comment by lit26** [comment]
You need to call the function multiple times or use the filter on the dataframe as finviz doesn't support multiple exchanges
