### ISSUE TITLE
Screneer pagination

### ISSUE THREAD

**Issue by gianlukk994** [lit26/finvizfinance#29]
Hi! 

Is it possible to provide pagination to the screener? 
I'm using the Custom class in this way:

```python
from finvizfinance.screener.custom import Custom

filters = {...something here}

foverwiew = Custom()
foverwiew.set_filter(filters_dict=filters)
df = foverwiew.ScreenerView(limit=20, order='Change',ascend=False, columns[0,1,2,3,4,5,6,7,16,17,22,23,33,36,37,38,65,66,67,68])
```

The problem is that I have to set a limit, otherwise the request could take too much time to be executed. 
Is there a way to add pagination? 

Thank you so much.

**Comment by lit26** [comment]
Sure, that will be done in the next version

**Comment by gianlukk994** [comment]
Awesome! Let me know if I can contribute in any way.

Thank you!

**Comment by gianlukk994** [comment]
Awesome! Let me know if I can contribute in any way.

Thank you!

**Comment by lit26** [comment]
The package is updated. Please check the new version. Thank you for your advice.
