### ISSUE TITLE
Asc and Desc sort options

### ISSUE THREAD

**Issue by gkye** [lit26/finvizfinance#3]
Hello, is it currently possible to use `Asc` or `Desc` for sorting?
The default is `Asc`, would it be possible to change it to `Desc` if needed? 
I've attempted `order=ticker asc` & `order=ticker desc` but no luck there. seems only the criteria order is respected not the sort

## Current
`foverview.ScreenerView(order='Analyst Recommendation',  limit=limit)`

## Want?
`foverview.ScreenerView(order='Analyst Recommendation', sort='asc', limit=limit)`

(Willing to make a PR if I could get some direction 😅 )

**Comment by lit26** [comment]
Currently, this is not available. But there is a very easy way to reverse the data frame like: 
```python
df[::-1]
```
If you think it is necessary, you can make a PR.

**Comment by lit26** [comment]
If you have no questions, this issue will be closed in 10 days. Thank you for your advice. 

Tianning Li
