### ISSUE TITLE
ImportError: cannot import name 'finviznews' from 'finvizfinance.news'

### ISSUE THREAD

**Issue by DavidRavnsborg** [lit26/finvizfinance#30]
Following along with the README.md. Importing and calling anything from finvizfinance.quote work perfectly, but importing finvizfinance.news give me:
`ImportError: cannot import name 'finviznews' from 'finvizfinance.news'`

The issue is that the News class in finvizfinance.news has been renamed. The fix is either to update the README.md file to alias the news module: `from finvizfinance.news import News as finviznews`, or to otherwise account for the re-name.

**Comment by lit26** [comment]
Yup, you are right. I have renamed the files in the later packages and didn't change the readme. The bug is fixed. Thanks for your contribution.
