### ISSUE TITLE
stock.ticker_fundament() is not working

### ISSUE THREAD

**Issue by plajos1** [lit26/finvizfinance#38]
Since yesterday (29.12) the stock.ticker_fundament() does not work. Maybe some change on the webpage and the scraper cannot cope with it...

**Comment by andersonwinkler** [comment]
I'm having the same problem...

```
  File "[REDACTED]/.local/lib/python3.7/site-packages/finvizfinance/quote.py", line 124, in ticker_fundament
    fundament_info["Company"] = rows[1].text
```

**Comment by plajos1** [comment]
In quote.py the function "ticker_fundament()" refers to the 5th table in the soup, but it seems, that the page has been changed yesterday 14:00ET, so the 4th table contains the necessary data:
"table = self.soup.findAll("table")[4]" will help. 
Maybe there are more issues, but this is the was the problem.

**Comment by andersonwinkler** [comment]
Many thanks. This worked for me (i.e., change to use table 4). Thanks thanks!

**Comment by lit26** [comment]
This issue is fixed in the latest version. Thank you all.
