### ISSUE TITLE
FinViz Fundamentals

### ISSUE THREAD

**Issue by dubleigh** [lit26/finvizfinance#43]
Hello,
It seems as if the FinViz fundamentals endpoint has lost functionality, and I can't seem to get the new code to work correctly

Here is the code:

    from finvizfinance.quote import finvizfinance
    stock = finvizfinance(ticker)
    stock_fundamentals = stock.ticker_fundament()
    print(stock_fundamentals)

Here is the error:
AttributeError: 'finvizfinance' object has no attribute 'ticker_fundament

Thank you!

**Comment by lit26** [comment]
![image](https://user-images.githubusercontent.com/51225681/156910333-f0885e02-1481-42c9-8342-b2c72ba2f070.png)
Please check the package version you are using.

**Comment by dubleigh** [comment]
Thank you! Just force reinstalled the package and that fixed it.

**Comment by lit26** [comment]
I guess you used an older package version while the code is the latest.
