### ISSUE TITLE
Fetching list of tickers returns 'NoneType'

### ISSUE THREAD

**Issue by D1al-T0ne** [lit26/finvizfinance#44]
Just curious what has changed with fetching a list of just tickers based on filters?

**Comment by lit26** [comment]
It seems I didn't implement that. I will update the module in the next version.

**Comment by lit26** [comment]
I miss understanding your question. If you get NoneType, there is no stock under your custom filters. The filters are also working in `finvizfinance.ticker`.

**Comment by D1al-T0ne** [comment]
Running a quick filter for tickers on 'NYSE' returns 'No ticker found'
Please point out what I may be doing wrong.
`from finvizfinance.screener.ticker import Ticker`
`tickers = Ticker()`
`filters_dict = {'Exchange': 'NYSE'}`
`tickers.set_filter(filters_dict=filters_dict)`
`df = tickers.ScreenerView()`
`No ticker found.`
Thanks for your help.

**Comment by D1al-T0ne** [comment]
I have noticed the changes, hence my original question. I have updated the module to the latest version. The docs are missing examples for Ticker.

**Comment by lit26** [comment]
Sorry, I didn't understand your problem. If rewriting your code, it is shown below.
![image](https://user-images.githubusercontent.com/51225681/160713831-084562a7-e4a8-45f3-9a5b-391d3c44c4e3.png)

**Comment by D1al-T0ne** [comment]
All good! 
This was a combination of issues.
When the first error occurred I tried screener_view() but had adjusted my code in trying to address the issue.
All straightened out.
Thanks for the help.

**Comment by lit26** [comment]
No problem.
