### ISSUE TITLE
table change for overview 

### ISSUE THREAD

**Issue by JerBouma** [lit26/finvizfinance#46]
Hey @lit26, within **group.overview** the table value on line 85 needs to be changed. Currently this is set to `table = soup.findAll("table")[5]` but should be `table = soup.findAll("table")[7]`. Could you fix this minor detail please?

**Comment by lit26** [comment]
It seems multiple pages on finviz have changed. I will check the full package.

**Comment by lit26** [comment]
The package is updated. Please check the new version. Thank you for your reporting.

**Comment by lit26** [comment]
Is the issue you mentioned related to the package and is the issue solved since it is merged?

**Comment by lit26** [comment]
Hi @JerBouma, not sure if this creates the problem. [Your test](https://github.com/OpenBB-finance/OpenBBTerminal/runs/5728731930?check_suite_focus=true) line 877, the group parameter should be like `Sector`, `Industry` ...

**Comment by JerBouma** [comment]
Hi @lit26, yes it relates to that indeed. The reason we haven't updated yet is due to the fact that it does break some other commands as well in a different area of our package which is most likely due to our own code. Therefore, we are not updating just yet. Thanks for the heads up nonetheless though!

**Comment by lit26** [comment]
No worries. Feel free to post issues if any.
