### ISSUE TITLE
New "Maps" feature in screener view is messing up the columns that are pulled when using finviz screener

### ISSUE THREAD

**Issue by jwalkingjew** [lit26/finvizfinance#48]
Code has been working for months. However, now that the new maps feature was added, the screener_view functionality is no longer working.

This is the code I am using:
foverview = Custom()
cols = list(range(0, 68))
filters_dict = {'Market Cap.':'+Mid (over $2bln)','RSI (14)':'Oversold (40)'}
#filters_dict = {'Market Cap.':'+Mid (over $2bln)'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view(order='LT Debt/Equity', columns=cols)

And it is pulling these columns, instead of the correct ones:
Valuation | Financial | Ownership | Performance | Technical | Custom | Charts | Tickers | Basic | TA | News | Snapshot | \n\n\nMaps\r\n | Stats

**Comment by lit26** [comment]
This issue should be fixed early today. The version is updated to v0.13.0. Please check the package version.
