### ISSUE TITLE
Issue with screener

### ISSUE THREAD

**Issue by joisaac** [lit26/finvizfinance#5]
I tried the same code as in the README file and I got this on Google Colab:
![Screenshot_2021-01-10_16-02-28](https://user-images.githubusercontent.com/60485595/104133990-6c5c8a00-535d-11eb-8027-db332217e765.png)

**Comment by lit26** [comment]
![finvizfinance](https://user-images.githubusercontent.com/51225681/104138674-8779ca80-535a-11eb-9e30-984955f61304.png)
I have tried on Google Colab myself which doesn't have the problem. Maybe try some other functions and/or update the packages.

**Comment by joisaac** [comment]
I don't get it but I had: `foverview.set_filter(filters_dict)` instead of `foverview.set_filter(filters_dict=filters_dict)` now it's working correctly

**Comment by joisaac** [comment]
Just one question before you close this, how can I get an Industry P/E ratio like [here](https://finviz.com/groups.ashx?g=industry&v=120&o=pe)

**Comment by lit26** [comment]
It is under finvizfinance.group.valuation

**Comment by lit26** [comment]
You can view the example in the example folder of this package.

**Comment by joisaac** [comment]
Good, thank you very much!

**Comment by lit26** [comment]
This issue will be closed in one day. Thank you for your advice.

Tianning Li

**Comment by lit26** [comment]
FYI, filter_dict is not the first parameter in the function so you need to pass in the parameter name.
