### ISSUE TITLE
BUG: screener_view not retrieving any results

### ISSUE THREAD

**Issue by h1ghco** [lit26/finvizfinance#52]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
overview = Overview()
    filters_dict = {'Index':'S&P 500','Sector':'Basic Materials'}
    overview.set_filter(filters_dict=filters_dict)
    df = overview.screener_view()
    df.head()
```

### Issue Description

Hi,

unfortunately somehow I am not getting any results any more using the Screener.
Strangely it is still downloading something but the response is only a empty Dataframe with defined Columns regarding the different views. 

See the example here:

![grafik](https://user-images.githubusercontent.com/35348935/164890448-f715b85d-b9ce-453b-a230-e933ad0da047.png)

### Expected Behavior

Expected Result is a DataFrame with the content of finviz pages (Overview / Custom / Performance) etc.

### Installed Versions

<details>

'0.12.2'

</details>

**Comment by lit26** [comment]
Version 0.12.2 no longer works. Please upgrade the package to the latest version 0.14.0.
