### ISSUE TITLE
BUG: Insider Page is not giving the error.

### ISSUE THREAD

**Issue by huzaifazahoor** [lit26/finvizfinance#54]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
from finvizfinance.insider import Insider
finsider = Insider()
insider_trader_df = finsider.get_insider()
```

### Issue Description

Whenever we call the **Insider()** class. It throws a below error:

> AttributeError: 'NoneType' object has no attribute 'findAll'

I think it is throwing the error because of Finviz Restrictions to get only the insider data from the insider page. You should use different **user agents** to see, how we can make this work.

### Expected Behavior

It should get the Data Frame, like how you have used it. Please work on it.

### Installed Versions

<details>

finvizfinance.0.14.1

</details>

**Comment by lit26** [comment]
This issue is fixed in the new version. Thanks for reporting.
