### ISSUE TITLE
BUG: missing Ticker: X when filters_dict = {'Sector':'Basic Materials','Market Cap.':'Mid ($2bln to $10bln)'}

### ISSUE THREAD

**Issue by myduffy** [lit26/finvizfinance#58]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
from finvizfinance.screener.overview import Overview

filters_dict = {'Sector':'Basic Materials','Market Cap.':'Mid ($2bln to $10bln)'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view()
df
```

### Issue Description

The last row is missing "Ticker: X", when compare finviz website

### Expected Behavior

include "Ticker:X" in last row.

### Installed Versions

<details>

finvizfinance in /jupyter/notebookenv/lib/python3.10/site-packages (0.14.3)

</details>

**Comment by lit26** [comment]
I have the ticker X on my side. Can you confirm?

**Comment by myduffy** [comment]
Hi ,

Yes, the results have ticker X now. And total have 59 items.




從我的iPhone傳送

Tianning Li ***@***.***>於2022年10月11日 下午3:56寫道：

﻿

I have the ticker X on my side. Can you confirm?
