### ISSUE TITLE
BUG: Insider SEC Form 4 Link 'NoneType' object has no attribute 'attrs’

### ISSUE THREAD

**Issue by CyberCouncil** [lit26/finvizfinance#60]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
from finvizfinance.insider import Insider

finsider = Insider(option='latest')
insider_trader = finsider.get_insider()
```

### Issue Description

Whenever we call the get_insider(). It throws a below error:

File “finvizfinance/insider.py”, line 81, in get_insider
info_dict[“SEC Form 4 Link”] = col.find(“a”).attrs[“href”]
AttributeError: 'NoneType' object has no attribute 'attrs’

### Expected Behavior

Get the Insider data

### Installed Versions

<details>

finvizfinance 0.14.3

</details>

**Comment by lit26** [comment]
Will be fixed in the next version.
