### ISSUE TITLE
README_pypi missing from repository

### ISSUE THREAD

**Issue by matthiasbeyer** [lit26/finvizfinance#64]
https://github.com/lit26/finvizfinance/blob/07046bbdbac7271a80c972d2842aab57c24a388d/setup.py#L14

This fails when using this package.

**Comment by lit26** [comment]
> https://github.com/lit26/finvizfinance/blob/07046bbdbac7271a80c972d2842aab57c24a388d/setup.py#L14
> 
> 
> 
> This fails when using this package.

Why you need this one? This is only for me to build the package.

**Comment by matthiasbeyer** [comment]
Yes, and packaging it is not easily possible without it... at least not with without hacks.

**Comment by lit26** [comment]
> Yes, and packaging it is not easily possible without it... at least not with without hacks.

Why you need packaging? This is only for me to publish on Pypi.

**Comment by matthiasbeyer** [comment]
Because I am packaging an application for my distro that uses this library.

**Comment by lit26** [comment]
Fixed. Please check
