### ISSUE TITLE
QST: type object 'finvizfinance' has no attribute 'Statements'

### ISSUE THREAD

**Issue by jackyzhang43** [lit26/finvizfinance#66]
### Question about finvizfinance

When I try to use the code defined [here](https://finvizfinance.readthedocs.io/en/latest/quote.html#finvizfinance.quote.Statements) I keep getting the error "type object 'finvizfinance' has no attribute 'Statements'." Why is this happening?

**Comment by lit26** [comment]
I think you missing `quote` in import.
```
from finvizfinance.quote import Statements
```

**Comment by lit26** [comment]
Close due to inactivity
