### ISSUE TITLE
screener - list index out of range

### ISSUE THREAD

**Issue by cwallace** [lit26/finvizfinance#7]
>   File "market_alerts.py", line 71, in getAlerts
>     df = foverview.ScreenerView(verbose=False)
>   File "/home/wallace/.local/lib/python3.8/site-packages/finvizfinance/screener/overview.py", line 232, in ScreenerView
>     page = self._get_page(soup)
>   File "/home/wallace/.local/lib/python3.8/site-packages/finvizfinance/screener/overview.py", line 178, in _get_page
>     options = soup.findAll('table')[17].findAll('option')
> IndexError: list index out of range

I'm receiving index out of range errors seemingly at random. Any idea if this is FinViz not returning expected results or if this is something that can be solved for?

**Comment by lit26** [comment]
Currently, I don't know what's the problem. Do you set any filters or signals?

**Comment by lit26** [comment]
This issue will be closed due to inactivity.

**Comment by VincentDuf** [comment]
Hi,
it seems that it happens when you have too few filters as it will ask for a lot of pages to load... 
I had the same issue but adding more "conditions" will do the trick. Loading 2 pages of 10 tickers each works.

**Comment by lit26** [comment]
Good to know. Thanks for helping.
