### ISSUE TITLE
ENH: Handle Finviz night mode

### ISSUE THREAD

**Issue by VadimKovalchuk** [lit26/finvizfinance#71]
#### Is your feature request related to a problem?

Failed to get stock fundamental data due to DOM change when Finviz automaticaly chalange UI with night mode

#### Describe the solution you'd like

Externally no changes should be observed 

#### API breaking implications

No API change is required

#### Describe alternatives you've considered

Force day mode of handle night mode

#### Additional context
Night mode representation:
<tbody><tr class="text-blue-500"><td align="center"><a href="quote.ashx?t=MSFT&amp;ty=c&amp;ta=1&amp;p=d" class="tab-link" id="ticker">MSFT</a> | <span><a href="https://www.microsoft.com" target="_blank" class="tab-link" rel="nofollow"><b>Microsoft Corporation</b></a></span> | <span class="body-table">[NASD]</span></td></tr>
<tr><td align="center" class="fullview-links"><a href="screener.ashx?v=111&amp;f=sec_technology" class="tab-link">Technology</a> | <a href="screener.ashx?v=111&amp;f=ind_softwareinfrastructure" class="tab-link">Software - Infrastructure</a> | <a href="screener.ashx?v=111&amp;f=geo_usa" class="tab-link">USA</a></td></tr>
</tbody>
There is only 2 table rows (code calls for 3rd one) 

```python
# Your code here, if applicable

```

**Comment by lit26** [comment]
#73 This will fix the issue. I will probably make a new release soon.

**Comment by lit26** [comment]
Should be fixed in #73. Release in v0.14.6rc1. Thanks for reporting.

**Comment by liorovadia** [comment]
Hello,

Is the bug still open or I'm missing something?
I tried to update to release v0.14.6rc1 (in the pycharm IDE) and got the following:

  File "C:\Users\~~~~~~~\PycharmProjects\~~~~~~\venv\lib\site-packages\finvizfinance\quote.py", line 145, in ticker_fundament
    (_, fundament_info["Company"], _) = rows[0].text.split(' | ')
ValueError: not enough values to unpack (expected 3, got 2)

Thank you lit26 for all your work

**Comment by lit26** [comment]
Yeah, there is still an issue. Fix soon.
