### ISSUE TITLE
FINVIZFINANCE ISSUE WHEN GETTING TICKER INFO

### ISSUE THREAD

**Issue by vfmas15** [lit26/finvizfinance#74]
**When I use:**

from finvizfinance.quote import finvizfinance

stock = finvizfinance('tsla')
stock.ticker_fundament()

**I get:**
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last) 
stock = finvizfinance('tsla')
stock.ticker_fundament()

in finvizfinance.ticker_fundament(self, raw, output_format)
    134 rows = table.findAll("tr")
    136 fundament_info["Company"] = rows[1].text
    137 (
    138     fundament_info["Sector"],
    139     fundament_info["Industry"],
    140     fundament_info["Country"],
--> 141 ) = rows[2].text.split(" | ")
    143 fundament_table = self.soup.find("table", class_="snapshot-table2")
    144 rows = fundament_table.findAll("tr")

IndexError: list index out of range

Any clue???

**Comment by lit26** [comment]
The website now have light and dark mode which show differently. I am currently looking into this.

**Comment by lit26** [comment]
Should be fixed in #73. Thanks for reporting.
