### ISSUE TITLE
BUG: failed to generate ticker outer ratings

### ISSUE THREAD

**Issue by kalabharath** [lit26/finvizfinance#85]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
>>> ticker = 'PLTR'
>>> stock = finvizfinance(ticker)
>>> outer_ratings_df = stock.ticker_outer_ratings()
>>> print (outer_ratings_df)
None
```

### Issue Description

its 'None' irrespective of ticker

### Expected Behavior

dataframe of analyst ratings

### Installed Versions

<details>

Replace this line with the output of finvizfinance.__version__

</details>

**Comment by lit26** [comment]
Should be fixed in the latest. Please check
