### ISSUE TITLE
ENH: Extra Columns Available for Custom Table

### ISSUE THREAD

**Issue by ljilekor** [lit26/finvizfinance#86]
Some columns are not available in the 'Custom' table.
[finvizfinance provides columns 0 to 70](https://github.com/lit26/finvizfinance/blob/master/finvizfinance/screener/custom.py)

But finviz has a few more columns: 
https://finviz.com/screener.ashx?v=152&c=73,%2075,%2076,%2077,%2078,%2079,%2080,%2081,%2082,%2083,%2084,%2085,%2086,%2087,%2088

```
non_implemented_col_ids = [73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]

EXTRA_COLUMNS = {
 73 : 'Book Value per Share',
 75 : 'Dividend',
 76 : 'Employees',
 ...
 86 : 'Open'
 87 : 'High',
 88 : 'Low',
}
```

For the sake of cleanness, completeness and because this is an easy fix,
I was going to fiddle with the base code.
But after seeing that the Sept 28 issue got fixed very quickly (big up @lit26 !), it may be better to implement this properly in the original code?

Any chance to see this implemented soon?

**Comment by lit26** [comment]
Should be fixed in the latest. Please check

**Comment by ljilekor** [comment]
Thanks @lit26 !! Great stuff.
I saw you added the missing columns to screener.custom.py

But after doing a 'pip install finvizfinance', I get only the old 70 columns... (v 0,14.6)
`from finvizfinance.screener.custom import COLUMNS`

Am I doing something wrong?

**Comment by lit26** [comment]
Use the pre-release version. The latest is v0.14.7rc2.

**Comment by ljilekor** [comment]
Great 
`pip install finvizfinance==0.14.7rc2`
did the trick!

Thx @lit26 for the quick response.
