### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by kahlijah** [lit26/finvizfinance#89]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
from finvizfinance.screener.overview import Overview
foverview = Overview()
filters_dict = {'Country':'USA'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view()
df.head()
```

### Issue Description

[Info] loading page [------------------------------] 1/373 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\KOMLAA~1\AppData\Local\Temp/ipykernel_11904/1391103343.py in <module>
      3 filters_dict = {'Country':'USA'}
      4 foverview.set_filter(filters_dict=filters_dict)
----> 5 df = foverview.screener_view()
      6 df.head()

~\Anaconda3\lib\site-packages\finvizfinance\screener\overview.py in screener_view(self, order, limit, select_page, verbose, ascend, sleep_sec)
    278 
    279         table = soup.find("table", class_="table-light")
--> 280         rows = table.findAll("tr")
    281         table_header = [i.text.strip() for i in rows[0].findAll("td")][1:]
    282         num_col_index = [table_header.index(i) for i in table_header if i in NUMBER_COL]

AttributeError: 'NoneType' object has no attribute 'findAll'

### Expected Behavior

The screener_view module is no longer working.

### Installed Versions

(0.14.6)

**Comment by lit26** [comment]
Use the pre-release version. The latest is v0.14.7rc2.

**Comment by kahlijah** [comment]
Do you have a script to help me install the pre-release version please?

**Comment by lit26** [comment]
pip install finvizfinance --pre

**Comment by kahlijah** [comment]
Thank you so much. I tried pip install finvizfinance==v0.14.7rc2 and it worked
