### ISSUE TITLE
 QST:  Hello Li - I'm getting an error 'An error occurred: 'NoneType' object has no attribute 'findAll' when running the script below. Is there an update to the library that can help me fix it please?

### ISSUE THREAD

**Issue by kahlijah** [lit26/finvizfinance#96]
### Question about finvizfinance

#High level stock data
try:
    foverview = Overview()
    filters_dict = {'Country':'USA'}
    foverview.set_filter(filters_dict=filters_dict)
    df = foverview.screener_view()
    df=df.rename(columns = {'Ticker\n\n':'Ticker'})
    df['P/E'] = df['P/E'].apply(pd.to_numeric,errors='coerce')
    df=df.rename(columns = {'Ticker':'symbol'})
except Exception as e:
    print(f"An error occurred: {e}")

**Comment by lit26** [comment]
I think you are using the older version. The latest version is 0.14.7. Can you check the version of the package? The latest bs4 switch `findAll` to `find_all`. The package also update this.

**Comment by kahlijah** [comment]
Thank you very much as always, Tianning!! Much appreciated!
