### ISSUE TITLE
ENH: Provide an API to obtain dividend history

### ISSUE THREAD

**Issue by random-developer** [lit26/finvizfinance#97]
I wish I could use finvizfinance to obtain a dividend history for a stock.

For example, I'd like to be able to:

```python
stock = finvizfinance('aapl')
dividend_history = stock.ticker_dividend_history()
```

where the returned value is a data frame of at least date and amount. For a more complete example, columns should be exdividend date, payment date, announcement_date, dividend_amount, and perhaps others. If the stock is one that has never had a dividend, either None (my preference) or an empty data frame would be ok.

**Comment by tli26** [comment]
There is no dividend history on the page
