### ISSUE TITLE
BUG: overview.screener_view

### ISSUE THREAD

**Issue by shahab-cl** [lit26/finvizfinance#99]
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
The following code does not stop even though the limit value is set.

    foverview = Overview()
    filters_dict = {'Average Volume':'Over 500K'}
    foverview.set_filter(filters_dict=filters_dict)
    df = foverview.screener_view(limit = 1, verbose = 1)
    df.head()
```

### Issue Description

Please see aboove

### Expected Behavior

should only return the number of rows = limit

### Installed Versions

<details>

finvizfinance       0.14.7
</details>

**Comment by lit26** [comment]
Should be fixed in the latest.
